Repository gitkoshelew/CC.api, pull requests merged in 2023-01, with the labels that each got.

#20 Feature/17 were created permissions tables
  src/access-group/access-group.controller.ts
  src/access-group/access-group.model.ts
  src/access-group/access-group.module.ts
  src/access-group/access-group.service.ts
  src/access-group/access-permission.model.ts
  src/access-group/dto/access-group.dto.ts
  src/app.module.ts
  src/permission/dto/create-permission.dto.ts
  src/permission/permission.controller.ts
  src/permission/permission.model.ts
  src/permission/permission.module.ts
  src/permission/permission.service.ts
  yarn.lock
Labels: task, Backend

#26 Creating relationship
  .idea/CC.api.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  package-lock.json
  package.json
  src/access-group/access-group.controller.ts
  src/access-group/access-group.model.ts
  src/access-group/access-group.module.ts
  src/access-group/access-group.service.ts
  src/access-group/access-permission.model.ts
  src/access-group/dto/access-group.dto.ts
  src/access-group/dto/addPermissionToAccess.dto.ts
  src/app.module.ts
  src/main.ts
  src/moderation/dto/create-moderation.dto.ts
  src/moderation/moderation.controller.ts
  src/moderation/moderation.model.ts
  src/moderation/moderation.service.ts
  src/permission/dto/create-permission.dto.ts
  src/permission/permission.controller.ts
  src/permission/permission.model.ts
  src/permission/permission.module.ts
  src/permission/permission.service.ts
  src/questions/dto/create-question.dto.ts
  src/questions/questions.controller.ts
  src/questions/questions.model.ts
  src/questions/questions.module.ts
  src/questions/questions.service.ts
  src/questions/questions.types.ts
  src/quiz/dto/addQuestion.dto.ts
  src/quiz/dto/create-quiz.dto.ts
  src/quiz/quiz.controller.ts
  src/quiz/quiz.model.ts
  src/quiz/quiz.module.ts
  src/quiz/quiz.question.model.ts
  src/quiz/quiz.service.ts
  src/topic/dto/create-topic.dto.ts
  src/topic/topic.controller.ts
  src/topic/topic.model.ts
  src/topic/topic.service.ts
  src/user/dto/addAccessToUser.dto.ts
  src/user/dto/create-user.dto.ts
  src/user/user.access.model.ts
  src/user/user.controller.ts
  src/user/user.model.ts
  src/user/user.module.ts
  src/user/user.service.ts
  yarn.lock
Labels: Backend

#36 fix: rewrite some descriptions for swagger
  src/moderation/moderation.controller.ts
  src/moderation/moderation.model.ts
  src/moderation/moderation.module.ts
  src/moderation/moderation.service.ts
  src/questions/dto/addModerationToQuestion.dto.ts
  src/questions/dto/create-question.dto.ts
  src/questions/questions.controller.ts
  src/questions/questions.model.ts
  src/questions/questions.module.ts
  src/questions/questions.service.ts
  src/questions/questions.types.ts
  src/quiz/dto/addQuestion.dto.ts
  src/quiz/dto/create-quiz.dto.ts
  src/quiz/quiz.model.ts
  src/topic/topic.model.ts
  src/user/user.controller.ts
  src/user/user.model.ts
  src/user/user.service.ts
Labels: Subtask, Backend

#47 added description field to quiz
  .idea/workspace.xml
  src/quiz/dto/create-quiz.dto.ts
  src/quiz/quiz.model.ts
Labels: Subtask, Backend

#46 Feature/32 was created jwt authorization
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorators/cookies.decorator.ts
  src/auth/decorators/users.decorator.ts
  src/auth/dto/login-user.dto.ts
  src/auth/dto/user-req.dto.ts
  src/auth/jwt-auth.guard.ts
  src/main.ts
  src/questions/questions.controller.ts
  src/questions/questions.module.ts
  src/quiz/dto/create-quiz.dto.ts
  src/quiz/quiz.controller.ts
  src/quiz/quiz.module.ts
  src/quiz/quiz.service.ts
  src/user/user.service.ts
Labels: task, Backend
